### ISSUE TITLE
Register GameServers with local IP addresses

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#469]
## Problem
For development/QA purposes, it is useful to be able to register a gameserver with Agones, but overwrite it with a specific local IP address, so that it can run through the same Agones system, but QA testers can connect to it, without having to do a full build + deploy pipeline.

## Design
We assume all port configuration should be `static`.
If the `GameServer` has an annotation of: `stable.agones.dev/dev-address: "192.168.0.1"` then we intercept this in the controller:
1. Don't create a Pod
2. Use this as the `Status.State` address.
3. Static port configurations are moved directly into `Status.Ports`
3. Automatically mark this `GameServer` as `Ready`.

## Example:

```yaml
apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServer
metadata:
  name: "xonotic"
  annotations:
    stable.agones.dev/dev-address: "192.168.0.1"
spec:
  ports:
    - name: default
      portPolicy: static
      containerPort: 26000
      hostPort: 26000
  template:
    spec:
      containers:
        - name: xonotic
          image: gcr.io/agones-images/xonotic-example:0.4
```

## Questions
- Do we like the name of the annotation?
