### ISSUE TITLE
Custom nodeAffinity for fleet

### ISSUE THREAD

**Issue by Oleksii-Terekhov** [GoogleCloudPlatform/agones#801]
**What happened**:
- write nodeAffinity for fleet
- try helm install custom helm chart
- got helm error 
```
Error from server (InternalError): error when creating "qq": Internal error occurred: failed calling admission webhook "mutations.stable.agones.dev": an error on the server ("") has prevented the request from succeeding
```
- remove affinity section
- success helm install

**What you expected to happen**:
- GS pod's with affinity

**How to reproduce it (as minimally and precisely as possible)**:
- add to any fleet
```
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
...
spec:
...
  template:
    metadata:
...
    spec:
...
      template:
...
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - preference:
                matchExpressions:
                - key: agones
                  operator: Exists
                weight: 1

```

**Anything else we need to know?**:

**Environment**:
- Agones version: 0.8.1
- Kubernetes version (use `kubectl version`): 1.11 (OKD 3.11)
- Cloud provider or hardware configuration: bare-metal
- Install method (yaml/helm): both
- Troubleshooting guide log(s):
```
controller log:
{"error":"error with webhook handler for path /mutate: error unmarshalling original Fleet json: {\"apiVer.....
}}}: json: cannot unmarshal array into Go struct field NodeAffinity.requiredDuringSchedulingIgnoredDuringExecution of type v1.NodeSelector","message":"","severity":"error","source":"*webhooks.WebHook","time":"2019-05-30T15:02:46.370320387Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=30s","Fragment":""}}
```
- Others: scheduling == Distributed

i wrote bad template or controller has extra filters in webhook?

**Comment by Oleksii-Terekhov** [comment]
trace:
```
[
"agones.dev/agones/pkg/util/webhooks.(*WebHook).handle\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:131",
"agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:99",
"net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964",
"net/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2361",
"net/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741",
"net/http.initNPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3291",
"net/http.(*initNPNRequest).ServeHTTP\n\t\u003cautogenerated\u003e:1",
"net/http.Handler.ServeHTTP-fm\n\t/usr/local/go/src/net/http/h2_bundle.go:5592",
"net/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5877",
"runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
]
```

**Comment by markmandel** [comment]
Quick question, I assume error was on `kubectl apply` (or similar api command), not on `helm install` ?

**Comment by markmandel** [comment]
Looking at the reference, looks like you are missing a `nodeSelectorTerms` under your `requiredDuringSchedulingIgnoredDuringExecution`

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#nodeselector-v1-core

**Comment by Oleksii-Terekhov** [comment]
- kubectl apply or helm install - both, (helm install) + (helm template+kubectl apply -f)

- my fault - in 1.11 absent "requiredDuringSchedulingIgnoredDuringExecution" without nodeSelectorTerms and not exist "requiredDuringScheduling**RequiredDuringExecution**"

Work fine with:
```
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
...
    spec:
...
      template:
...
        spec:
...
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: testnode
                    operator: Exists
```
